version: 1.0.{build}
cache: C:\Users\appveyor\.dnx\packages
before_build:
- cmd: dnvm upgrade
- cmd: dnu restore
build_script:
- cmd: dnu build src\Palantir.Numeric tst\Palantir.Numeric.UnitTests
test_script:
    - cmd: C:\Users\appveyor\.dnx\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -target:C:\Users\appveyor\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update2\bin\dnx.exe -targetargs:"--lib src\Palantir.Numeric -p tst\Palantir.Numeric.UnitTests test" -register:user -filter:+[Palantir]* -output:coverage.xml
    - cmd: C:\Users\appveyor\.dnx\packages\coveralls.io\1.3.4\tools\coveralls.net.exe --opencover coverage.xml
    #- cmd: dnx -p tst\Palantir.Numeric.UnitTests test
environment:
    COVERALLS_REPO_TOKEN:
        secure: RNtN37dGG1ZzLKHaFzvfLObwyda2Wjbn9
after_test: 
# generate report for NUnit testing framework:
    #-cmd: OpenCover.Console.exe "-target:artifacts\build\xunit.runner.console\Tools\xunit.console.exe" "-targetargs:C:\_PublishedXUnit\FW.WebAPI.Plugins.Tests\FW.WebAPI.Plugins.Tests.dll -xml C:\TestResults\XUnit\xUnit.xml -nologo -noshadow" "-output:C:\TestCoverage\OpenCover.xml" "-filter:+[*]* -[*Tests]* -[*xunit*]*" "-excludebyattribute:System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute" "-excludebyfile:*\*Designer.cs;*\*.g.cs;*\*.g.i.cs" -skipautoprops -mergebyhash -mergeoutput -hideskipped:All -returntargetcode -register:user -log:All
build:
  verbosity: normal